apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: "developer"
rules:
- apiGroups: [""]
  resources: ["pods"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get"]