apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: rm-service
  labels:
    app: rm-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: rm-service
  type: NodePort
  selector:
    app: rm-service