apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: dev
  name: cronjob-example
  labels:
    app: cronjob-example
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: '*/1 * * * *' # every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-example
              image: appropriate/curl
              args:
                - /bin/sh
                - -c
                - "curl --fail rm-gateway"
          restartPolicy: Never
      backoffLimit: 5