apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: rm-service
  labels:
    app: rm-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rm-service
  template:
    metadata:
      labels:
        app: rm-service
    spec:
      containers:
        - name: rm-service
          image: registry-intl-vpc.ap-southeast-3.aliyuncs.com/findev/kubernetes-example-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
              cpu: "25m"
            requests:
              memory: 25Mi
              cpu: "20m"